### ISSUE TITLE
Changing proxy port is uneffective

### ISSUE THREAD

**Issue by AmulyaReddy99** [Playork/StickyNotes#13]
**Changing port number opens port 8080 by default**
Every time I use this application, it doesn't open the notes in the specified port both before and after changing the proxy port to 7000 in 'vue.config.js' file.
 - OS: [e.g. MacOS]

**Comment by bekalshenoy** [comment]
Go to [Here](https://github.com/Playork/StickyNotes/blob/6240ca90f66aa4abce510f295da22980533b2e7a/src/background.js#L103) And Change The Port To Work
