### ISSUE TITLE
Share sticky notes

### ISSUE THREAD

**Issue by fabioalxk** [Playork/StickyNotes#15]
I have a girlfriend and we would like to share Sticky notes like shoplists.
When she goes to the supermarket, she checks her sticky note in her computer and she can buy the groceries for me.

I usually do a list of tasks for her aswell (to-do-list) like:
1) Visit her mother
2) Do the dishes
3) Go to the restaurant in a certain date

Right now I'm sending this info for her via whatsapp. But we usually forget about those things because they are out of our sight. We would like to have a shared note.

**Comment by bekalshenoy** [comment]
Thank You For The Feedback I Will Work On That
