### ISSUE TITLE
Releasing debian installer 

### ISSUE THREAD

**Issue by rahulpathakgit** [Playork/StickyNotes#4]
Hi, StickyNotes looks promising and I want to use it. Will you be able to release the debian installer for the app. I have tried to build it on my machine but failed.

**Comment by bekalshenoy** [comment]
which build you use 32bit or 64bit

**Comment by bekalshenoy** [comment]
added a deb package in release page for you works in both 32bit and 64bit

**Comment by bekalshenoy** [comment]
here
https://github.com/Playork/StickyNotes/releases/download/v0.1.0-beta.2/stickynotes_0.1.0.deb
