### ISSUE TITLE
Keep snap unlisted

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [Playork/StickyNotes#6]
Hello, just found the snap on <http://feeds.feedburner.com/UbuntuTouchNewApps>, it seems that you haven't properly packaged the snap yet, you might want to consider making it unlisted via the  <https://snapcraft.io/stickynotes/settings> page so it won't be listed in the search results and no one will accidentally installing it.

**Comment by bekalshenoy** [comment]
I packed it now for 64 bite go and check

**Comment by Lin-Buo-Ren** [comment]
I overlooked the snapcraft recipe, my bad. :man_facepalming:
